services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concepts_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/db:/var/lib/mysql
    networks:
      - mysql_network
networks:
  mysql_network:
