@baseUrl = http://localhost:3000

### AppControllerGet

# @name AppControllerGet
# @description This is a simple GET endpoint that returns a string.
# @method GET
# @path /
# @responses
# - status: 200
#   description: Returns a simple string.
#   body: "Hello World!"
# @tags
# - AppController
# @example
#   curl -X GET http://localhost:3000/
#   # Response: "Hello World!"
GET {{baseUrl}}/